apiVersion: 1

providers:
  - name: "ZQM Prometheus"
    orgId: 1
    folder: ""
    type: prometheus
    disableDeletion: false
    updateIntervalSeconds: 10
    allowUiUpdates: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.47
    editable: true
    options:
      url: http://prometheus:9090
